org: alecpm
app: kcrw-alexa-skill
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: kcrw-alexa-skill
frameworkVersion: ^2.70.0

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  memorySize: 512
  timeout: 3
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
          - "dynamodb:*"
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          - "lambda:InvokeFunction"
      Resource: "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-alexa-skills
functions:
  handler:
    handler: src/index.handler
    events:
      - alexaSkill: amzn1.ask.skill.1a8abcbc-1fca-4f61-b87e-12da026087ce

custom:
  alexa:
    vendorId: M3HBK4U0VC2544
    localServerPort: 9999
    skills:
      - id: amzn1.ask.skill.1a8abcbc-1fca-4f61-b87e-12da026087ce
        manifest:
          publishingInformation:
            locales:
              en-US:
                name: KCRW
          manifestVersion: '1.0'
        models:
          en:
            interactionModel:
              languageModel:
                invocationName: k. c. r. w.
                intents:
                - name: AMAZON.CancelIntent
                  samples: []
                - name: AMAZON.HelpIntent
                  samples: []
                - name: AMAZON.PauseIntent
                  samples: []
                - name: AMAZON.ResumeIntent
                  samples: []
                - name: AMAZON.StopIntent
                  samples:
                  - Exit
                - name: PlayIntent
                  slots:
                  - name: channel
                    type: channels
                  samples:
                  - play {channel}
                  - play
                  - listen to {channel}
                  - open {channel}
                  - stream {channel}
                  - stream
                - name: WhatIntent
                  slots:
                  - name: what
                    type: what_types
                  samples:
                  - who {what}
                  - what {what}
                  - who is {what}
                  - what is {what}
                  - what {what} is playing
                  - who is this {what}
                  - what is this {what}
                  - what {what} is this
                  - what {what} is playing now
                  - what is playing
                  - what is this
                  - what is playing now
                  - who is playing
                  - who is this
                  - who is playing now
                  - what {what} this is
                  - who this is
                  - what's playing
                  - who's playing
                  - who's this
                - name: AMAZON.NavigateHomeIntent
                  samples: []
                types:
                - name: channels
                  values:
                  - id: music
                    name:
                      value: music
                      synonyms:
                      - kcrw music
                      - k. c. r. w. music
                      - eclectic
                      - music stream
                      - live music
                      - eclectic twenty four
                      - eclectic24
                      - eclectic 24
                      - eclectic twentyfour
                      - e. twenty four
                      - e. 24
                      - e. twentyfour
                      - twenty four
                      - '24'
                      - twentyfour
                  - id: news
                    name:
                      value: news
                      synonyms:
                      - kcrw news
                      - k. c. r. w. news
                      - news twenty four
                      - news twentyfour
                      - news 24
                      - news stream
                      - live news
                  - id: live
                    name:
                      value: live
                      synonyms:
                      - kcrw
                      - simulcast
                      - live stream
                      - k.c.r.w.
                      - radio
                      - live radio
                - name: what_types
                  values:
                  - id: song
                    name:
                      value: song
                      synonyms:
                      - sings this track
                      - plays this track
                      - track
                      - song
                      - band
                      - sings this song
                      - plays this song
                      - playing this song
                      - singing this song
                      - singer
                  - id: show
                    name:
                      value: show
                      synonyms:
                      - d. j.
                      - host
                      - program
                      - d. j.'s this show
                      - d. j.'s this program
                      - hosts this program
                      - hosts this show
              _nameFreeInteraction:
                ingressPoints:
                - type: INTENT
                  sampleUtterances:
                  - format: RAW_TEXT
                    value: play k. c. r. w. music
                  - format: RAW_TEXT
                    value: play k. c. r. w. news
                  - format: RAW_TEXT
                    value: play eclectic twenty four
                  - format: RAW_TEXT
                    value: play k. c. r. w. eclectic twenty four
                  - format: RAW_TEXT
                    value: stream eclectic twenty four
                  name: PlayIntent
                - type: LAUNCH
                  sampleUtterances:
                  - format: RAW_TEXT
                    value: play k. c. r. w.
                  - format: RAW_TEXT
                    value: stream k. c. r. w.
                  - format: RAW_TEXT
                    value: play k. c. r. w. radio
                  - format: RAW_TEXT
                    value: stream k. c. r. w. radio
                - type: INTENT
                  sampleUtterances:
                  - format: RAW_TEXT
                    value: what song is this
                  - format: RAW_TEXT
                    value: what show is this
                  name: WhatIntent
